# 1. Import Libraries

In [1]:
#import libraries
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter
import seaborn as sns
import scipy

# 2 Import Data

In [2]:
path = r'/Users/golde/Crime Analysis/'

In [3]:
crimes = pd.read_csv(os.path.join(path, '2. Data', 'Original Data', 'crimes.csv'))

In [4]:
crimes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 30 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   ID                          1048575 non-null  int64
 1   Case Number                 1048575 non-null  object
 2   Date                        1048575 non-null  object
 3   Block                       1048575 non-null  object
 4   IUCR                        1048575 non-null  object
 5   Primary Type                1048575 non-null  object
 6   Description                 1048575 non-null  object
 7   Location Description        1045453 non-null  object
 8   Arrest                      1048575 non-null  bool
 9   Domestic                    1048575 non-null  bool
 10  Beat                        1048575 non-null  int64
 11  District                    1048574 non-null  float64
 12  Ward                        1022444 non-null  float64
 13  Community Area              1022556 non-null  float64
 14  FBI Code                    1048575 non-null  object
 15  X Coordinate                1043444 non-null  float64
 16  Y Coordinate                1043444 non-null  float64
 17  Year                        1048575 non-null  int64
 18  Updated On                  1048575 non-null  object
 19  Latitude                    1043444 non-null  float64
 20  Longitude                   1043444 non-null  float64
 21  Location                    1043444 non-null  object
 22  Historical Wards 2003-2015  1040970 non-null  float64
 23  Zip Codes                   1043444 non-null  float64
 24  Community Areas             1041419 non-null  float64
 25  Census Tracts               1041508 non-null  float64
 26  Wards                       1041437 non-null  float64
 27  Boundaries - ZIP Codes      1041430 non-null  float64
 28  Police Districts            1041551 non-null  float64
 29  Police Beats                1041558 non-null  float64
dtypes: bool(2), float64(15), int64(3), object(10)
memory usage: 226.0+ MB

In [5]:
pd.options.display.max_rows = None

In [6]:
pd.options.display.max_columns = None

In [7]:
crimes.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location,Historical Wards 2003-2015,Zip Codes,Community Areas,Census Tracts,Wards,Boundaries - ZIP Codes,Police Districts,Police Beats
0,10224738,HY411648,9/5/15 13:30,043XX S WOOD ST,486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,924,9.0,12.0,61.0,08B,1165074.0,1875917.0,2015,2/10/18 15:50,41.815117,-87.670000,"(41.815117282, -87.669999562)",29.0,14924.0,59.0,706.0,3.0,37.0,23.0,108.0
1,10224739,HY411615,9/4/15 11:30,008XX N CENTRAL AVE,870,THEFT,POCKET-PICKING,CTA BUS,False,False,1511,15.0,29.0,25.0,6,1138875.0,1904869.0,2015,2/10/18 15:50,41.895080,-87.765400,"(41.895080471, -87.765400451)",4.0,4299.0,26.0,562.0,45.0,5.0,25.0,67.0
2,11646166,JC213529,9/1/18 0:01,082XX S INGLESIDE AVE,810,THEFT,OVER $500,RESIDENCE,False,True,631,6.0,8.0,44.0,6,NaN,NaN,2018,4/6/19 16:04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10224740,HY411595,9/5/15 12:45,035XX W BARRY AVE,2023,NARCOTICS,POSS: HEROIN(BRN/TAN),SIDEWALK,True,False,1412,14.0,35.0,21.0,18,1152037.0,1920384.0,2015,2/10/18 15:50,41.937406,-87.716650,"(41.937405765, -87.716649687)",15.0,21538.0,22.0,216.0,12.0,39.0,7.0,168.0
4,10224741,HY411610,9/5/15 13:00,0000X N LARAMIE AVE,560,ASSAULT,SIMPLE,APARTMENT,False,True,1522,15.0,28.0,25.0,08A,1141706.0,1900086.0,2015,2/10/18 15:50,41.881903,-87.755121,"(41.881903443, -87.755121152)",11.0,22216.0,26.0,696.0,23.0,32.0,25.0,81.0

In [8]:
crimes = crimes.drop(columns = ['Historical Wards 2003-2015', 'Zip Codes', 'Community Areas', 'Boundaries - ZIP Codes', 'Police Districts', 'Police Beats'])

In [9]:
#check for missing values 
crimes.isnull().sum()

ID                          0
Case Number                 0
Date                        0
Block                       0
IUCR                        0
Primary Type                0
Description                 0
Location Description     3122
Arrest                      0
Domestic                    0
Beat                        0
District                    1
Ward                    26131
Community Area          26019
FBI Code                    0
X Coordinate             5131
Y Coordinate             5131
Year                        0
Updated On                  0
Latitude                 5131
Longitude                5131
Location                 5131
Census Tracts            7067
Wards                    7138
dtype: int64

In [10]:
crimes = crimes.dropna(how = 'any')

In [11]:
crimes.isnull().sum()

ID                      0
Case Number             0
Date                    0
Block                   0
IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
Ward                    0
Community Area          0
FBI Code                0
X Coordinate            0
Y Coordinate            0
Year                    0
Updated On              0
Latitude                0
Longitude               0
Location                0
Census Tracts           0
Wards                   0
dtype: int64

In [12]:
# duplicates
crimes_dups = crimes[crimes.duplicated()]

In [13]:
crimes_dups

Empty DataFrame
Columns: [ID, Case Number, Date, Block, IUCR, Primary Type, Description, Location Description, Arrest, Domestic, Beat, District, Ward, Community Area, FBI Code, X Coordinate, Y Coordinate, Year, Updated On, Latitude, Longitude, Location, Census Tracts, Wards]
Index: []

In [14]:
# checking for mixed types
for col in crimes.columns.tolist():
  weird = (crimes[[col]].applymap(type) != crimes[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (crimes[weird]) > 0:
    print (col)

In [15]:
#export data
crimes.to_csv(os.path.join(path, '2. Data','Prepared Data', 'crimes_cleaned.csv'))